apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus-server:80
    access: proxy
    isDefault: true
    
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy